# Generated by Django 4.0.5 on 2022-07-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Precio',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='favorito',
            field=models.BooleanField(default=False, verbose_name='Favoritio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imgProducto',
            field=models.ImageField(default='/default/default-prod.jpg', upload_to='Productos'),
        ),
    ]
