# Generated by Django 4.0.5 on 2022-07-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyP', '0003_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='', verbose_name='descripcion'),
        ),
    ]
