# Generated by Django 4.0.5 on 2022-07-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyP', '0004_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imgProducto',
            field=models.ImageField(default='/default/default-prod.jpg', upload_to='Productos/'),
        ),
    ]
